# Generated by Django 5.1.2 on 2025-12-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_type', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('post_description', models.TextField()),
            ],
        ),
    ]
